### ISSUE TITLE
Must wait 00:00 before submitting a new report

### ISSUE THREAD

**Issue by LaxSlash** [LaxSlash/Halo-CE-Discord-Reporter#12]
**Description:**
Lua script errors out saying a player must wait 00:00 before submitting a new report.

**Steps to reproduce:**
1) Submit a report
2) Leave the server
3) Rejoin after the timeout
4) Try to submit another report

**Expected Result:**
Another report is submitted.

**Actual Result:**
SAPP Responds "You must wait 00:00 before submitting a new report."

**Workaround:**
Reload SAPP after submitting a report.

**Comment by Devieth** [comment]
HOW DO I CLOSE THIS!
